In [ ]:
import numpy as np                                      #importing the libraries and reading the data
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from nltk import FreqDist

# original_data=pd.read_csv("data_avg_batsman_runs.csv")
# original_data
original_data= pd.read_csv("Btsmn_wk_New_features_avg.csv")


# original_data=original_data[original_data['batsman']=='V Kohli']
# val=original_data['strike_rate'].values
# fdist = FreqDist(val)
# fdist.most_common(2)
# print(val.mean())
# original_data=original_data.head(100)
original_data

Unnamed: 0 wicket_keeper_batsman  match_id              home_team  \
0              0              A Chopra        29  Kolkata Knight Riders   
1              1              A Chopra        32  Kolkata Knight Riders   
2              2              A Chopra        35  Kolkata Knight Riders   
3              3              A Chopra        38  Kolkata Knight Riders   
4              4              A Chopra        51  Kolkata Knight Riders   
...          ...                   ...       ...                    ...   
6571        6571          Yuvraj Singh       677        Kings XI Punjab   
6572        6572          Yuvraj Singh       681        Kings XI Punjab   
6573        6573          Yuvraj Singh       691        Kings XI Punjab   
6574        6574          Yuvraj Singh       703        Kings XI Punjab   
6575        6575          Yuvraj Singh       719        Kings XI Punjab   

                  opposition_team  \
0     Royal Challengers Bangalore   
1                 Deccan Chargers   
2                Delhi Daredevils   
3                  Mumbai Indians   
4                 Kings XI Punjab   
...                           ...   
6571  Royal Challengers Bangalore   
6572          Chennai Super Kings   
6573             Delhi Daredevils   
6574               Mumbai Indians   
6575               Mumbai Indians   

                                                  venue  inning  batsman_runs  \
0                                          Eden Gardens       1             2   
1             Rajiv Gandhi International Stadium, Uppal       1            24   
2                                          Eden Gardens       1            13   
3                                      Wankhede Stadium       1             1   
4                                          Eden Gardens       2             2   
...                                                 ...     ...           ...   
6571                              M.Chinnaswamy Stadium       1             4   
6572  Punjab Cricket Association IS Bindra Stadium, ...       1            20   
6573                                   Feroz Shah Kotla       1            14   
6574                             Holkar Cricket Stadium       1            14   
6575                                   Wankhede Stadium       2             1   

      sixes  fours  ...  avg_oppo_points  avg_venue_points  avg_inning_points  \
0         0      0  ...         2.000000          2.000000           2.000000   
1         0      3  ...        15.000000         15.000000           8.500000   
2         0      2  ...         7.000000          4.500000           8.000000   
3         0      0  ...         1.000000          1.000000           6.250000   
4         0      0  ...         2.000000          3.666667           2.000000   
...     ...    ...  ...              ...               ...                ...   
6571      0      1  ...        19.000000         10.500000          16.666667   
6572      1      2  ...        16.812500         14.000000          16.640625   
6573      0      1  ...        19.117647         14.700000          16.553846   
6574      1      0  ...        10.333333         11.000000          16.469697   
6575      0      0  ...         9.842105         11.100000          14.650000   

      avg_batsman_runs  avg_strike_rate  avg_home_team_points  bound_runs  \
0             2.000000        40.000000              2.000000           0   
1            13.000000        68.000000              8.500000          12   
2            13.000000        69.407407              8.000000           8   
3            10.000000        58.305556              6.250000           0   
4             8.400000        59.977778              5.400000           0   
...                ...              ...                   ...         ...   
6571         22.139344       111.455834             14.750000           4   
6572         22.121951       111.800471             14.755556          14   
6573         22.05645

In [ ]:
# plt.style.use('seaborn-whitegrid')
x = original_data["rating"].values    #storing the values of ratings in an array
encoded=[];                         
for w in x :                          #for loop over the rating column
    if(w==9):                         
        encoded.append("9")           #if w = 9; then encode it as 9  
    elif(w==9.5 ):                    
        encoded.append("9.5")         #if w = 9.5; then encode it as 9.5
    elif(w==10):
        encoded.append("10")          #if w = 10; then encode it as 10
    elif(w==8 ):
        encoded.append("8")           #if w = 8; then encode it as 8
    elif(w==8.5 ):
        encoded.append("8.5")         #if w = 8.5; then encode it as 8.5
    
encoded   
    
#     if(w>=0 and w<=20):
#         encoded.append(1)
#     if(w>20 and w<=49):
#         encoded.append(2)
#     if(w>49 and w<=74):
#         encoded.append(3)
# #     if(w>74 and w<=110):
# #         encoded.append(4)
#     if(w>74):
#         encoded.append(4)
        




['8',
 '8.5',
 '8.5',
 '8',
 '8.5',
 '8.5',
 '8',
 '8.5',
 '8',
 '9.5',
 '9',
 '9',
 '10',
 '8.5',
 '10',
 '9.5',
 '8',
 '9',
 '9',
 '8.5',
 '8.5',
 '8.5',
 '8',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '9',
 '8',
 '9',
 '9',
 '8',
 '8.5',
 '8.5',
 '8.5',
 '9.5',
 '8.5',
 '9',
 '8',
 '8',
 '9',
 '9',
 '9',
 '8.5',
 '9',
 '8.5',
 '8.5',
 '9',
 '8',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '9',
 '8.5',
 '9',
 '8.5',
 '8',
 '9',
 '9.5',
 '9',
 '9.5',
 '8.5',
 '9',
 '8',
 '8.5',
 '9',
 '9',
 '9',
 '8.5',
 '9',
 '8.5',
 '9.5',
 '9',
 '9.5',
 '8',
 '9',
 '10',
 '9.5',
 '8.5',
 '8',
 '8.5',
 '8.5',
 '9.5',
 '9',
 '8.5',
 '10',
 '8.5',
 '9',
 '9.5',
 '9.5',
 '9.5',
 '9',
 '10',
 '9.5',
 '8.5',
 '8.5',
 '8',
 '9',
 '9.5',
 '9',
 '9.5',
 '9.5',
 '9.5',
 '9.5',
 '9',
 '8.5',
 '9.5',
 '10',
 '9',
 '9',
 '9.5',
 '9',
 '9',
 '8',
 '9',
 '9.5',
 '9.5',
 '8.5',
 '8',
 '9.5',
 '8',
 '9.5',
 '9.5',
 '9',
 '9.5',
 '9',
 '9',
 '8.5',
 '8',
 '9.5',
 '8.5',
 '9.5',
 '9.5',
 '8',
 '8.5',
 '9',
 '8.5',
 '9.5',
 '8.5',
 '8.5'

In [ ]:
original_data['good_player']=encoded                                      #replacing the values in the column as the encoded values


le = preprocessing.LabelEncoder()                                         #Converting string labels into numbers

venue_encoded=le.fit_transform(original_data['venue'])                    #this will take the values of the venues in total and return it as encoded labels 
print(venue_encoded)

name_encoded=le.fit_transform(original_data['wicket_keeper_batsman'])     #this will take the values of the wicketkeeper batsman i.e. the role of the player is wicketkeeper batsman in total and return it as encoded labels 
print(name_encoded)

opp_team_encoded=le.fit_transform(original_data['opposition_team'])       #this will take the values of the opposition teams in total and return it as encoded labels 
print(opp_team_encoded)

original_data['venue_encoded']=venue_encoded                              #view the columns after encoding the labels
original_data['name_encoded']=name_encoded
original_data['opp_team_encoded']=opp_team_encoded

[ 7 24  7 ...  8 11 35]
[  0   0   0 ... 205 205 205]
[13  1  3 ...  3  8  8]


In [ ]:
# x=original_data[['name_encoded','venue_encoded','opp_team_encoded','batting_avg_inning_points','batting_avg_venue_points','batting_avg_oppo_points','avg_strike_rate','avg_batsman_runs','bowl_fp_avg','bowl_opp_avg','bowl_ven_avg','bowl_inn_avg','bowl_run_avg','eco_avg','maiden_avg','wicket_avg','bowl_over_avg']]
# x=original_data[['name_encoded','venue_encoded','opp_team_encoded']]
x=original_data[['name_encoded','venue_encoded','opp_team_encoded','avg_oppo_points','avg_venue_points','avg_inning_points','avg_batsman_runs','avg_strike_rate','avg_home_team_points','avg_total_points','avg_bound_runs']]
y=original_data['good_player']                                                        #taking required features or columns for the model training
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)    #dividing the train (75%) and test data (25%) with random state = 42 for data shuffling

model=GaussianNB()                                                                    #Naive Bayes model for classification
model.fit(x_train,y_train)                                                            #pass the training data in the model to predict the test data

y_test

611       9
4443    9.5
1419    8.5
5584     10
3094      9
       ... 
5870     10
344     9.5
2642      9
5084      9
911       9
Name: good_player, Length: 1644, dtype: object

In [ ]:
y_pred=model.predict(x_test)      #predicting y_test for x_test using the model
y_pred

array(['9', '9', '8.5', ..., '8.5', '10', '9'], dtype='<U3')

In [ ]:
accuracy=accuracy_score(y_test,y_pred)*100    #printing the test accuracy of the data
accuracy

37.95620437956204

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix   #confusion matrix for test data vs predicted data
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[108   2  18 110   1]
 [ 19 112 130  48   1]
 [ 34  77 234 169   5]
 [ 67  30 149 161   7]
 [ 23  15  45  70   9]]
              precision    recall  f1-score   support

          10       0.43      0.45      0.44       239
           8       0.47      0.36      0.41       310
         8.5       0.41      0.45      0.43       519
           9       0.29      0.39      0.33       414
         9.5       0.39      0.06      0.10       162

    accuracy                           0.38      1644
   macro avg       0.40      0.34      0.34      1644
weighted avg       0.39      0.38      0.37      1644



In [ ]:
from sklearn.model_selection import cross_val_score             #repeating the same steps for train and test data but using Random Forest Classifier
                                                                #accuracy is printed as well
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import RandomForestClassifier
x=original_data[['name_encoded','venue_encoded','opp_team_encoded','avg_oppo_points','avg_venue_points','avg_inning_points','avg_batsman_runs','avg_strike_rate','avg_home_team_points','avg_total_points','avg_bound_runs']]

# x=original_data[['name_encoded','venue_encoded','opp_team_encoded','batting_avg_inning_points','batting_avg_venue_points','batting_avg_oppo_points','avg_strike_rate','avg_batsman_runs' ,'bowl_fp_avg','bowl_opp_avg','bowl_ven_avg','bowl_inn_avg','bowl_run_avg','eco_avg','maiden_avg','wicket_avg','bowl_over_avg']]
# x=original_data[['name_encoded','venue_encoded','opp_team_encoded']]
# x=original_data[['name_encoded','venue_encoded','opp_team_encoded','avg_oppo_points','avg_venue_points','avg_inning_points','avg_batsman_runs','avg_strike_rate']]
# x=original_data[['name_encoded','venue_encoded','opp_team_encoded']]
# x=original_data[['name_encoded','venue_encoded','opp_team_encoded','avg_venue_points','avg_inning_points','avg_opposition_points','avg_batsman_runs','avg_strike_rate']]
y=original_data['good_player']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

rf = RandomForestClassifier(n_estimators=340)                   #Random Forest classifier with 340 decision trees 
rf.fit(x_train,y_train)


yhat = rf.predict(x_test)                                       #predicting the ytest using prediction of xtest

# t0 = time()
y_pred = rf.predict(x_test)
# print("done in %0.3fs" % (time() - t0))
print(classification_report(y_test, y_pred))                    #classification report for ytest vs ypred values

              precision    recall  f1-score   support

          10       0.56      0.51      0.54       239
           8       0.78      0.51      0.62       310
         8.5       0.48      0.61      0.54       519
           9       0.36      0.46      0.40       414
         9.5       0.44      0.12      0.19       162

    accuracy                           0.49      1644
   macro avg       0.53      0.44      0.46      1644
weighted avg       0.52      0.49      0.48      1644

