In [ ]:
import numpy as np                                          #importing the libraries and reading the data
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from nltk import FreqDist

# original_data=pd.read_csv("data_avg_batsman_runs.csv")
# original_data
original_data= pd.read_csv("ALL_ROUNDERS_AVG_POINTS.csv")


# original_data=original_data[original_data['batsman']=='V Kohli']
# val=original_data['strike_rate'].values
# fdist = FreqDist(val)
# fdist.most_common(2)
# print(val.mean())
# original_data=original_data.head(100)
original_data

all_rounder  match_id       batted_for  \
0        A Ashish Reddy       286  Deccan Chargers   
1        A Ashish Reddy       292  Deccan Chargers   
2        A Ashish Reddy       298  Deccan Chargers   
3        A Ashish Reddy       314  Deccan Chargers   
4        A Ashish Reddy       317  Deccan Chargers   
...                 ...       ...              ...   
4496            I Udana       784                0   
4497          CH Morris       784                0   
4498  Washington Sundar       784                0   
4499          PP Chawla       785                0   
4500           R Ashwin       786                0   

                  opposition_team                                      venue  \
0                  Mumbai Indians                           Wankhede Stadium   
1             Chennai Super Kings            MA Chidambaram Stadium, Chepauk   
2                 Kings XI Punjab  Rajiv Gandhi International Stadium, Uppal   
3                Rajasthan Royals  Rajiv Gandhi International Stadium, Uppal   
4     Royal Challengers Bangalore  Rajiv Gandhi International Stadium, Uppal   
...                           ...                                        ...   
4496        Kolkata Knight Riders                    Sharjah Cricket Stadium   
4497        Kolkata Knight Riders                    Sharjah Cricket Stadium   
4498        Kolkata Knight Riders                    Sharjah Cricket Stadium   
4499          Sunrisers Hyderabad        Dubai International Cricket Stadium   
4500             Rajasthan Royals        Dubai International Cricket Stadium   

      bat_inning  batsman_runs  balls  strike_rate  total_batting_points  ...  \
0              1            10     10        100.0                     7  ...   
1              2             3      3        100.0                     3  ...   
2              2             8      8        100.0                     5  ...   
3              2            10      4        250.0                     4  ...   
4              1             4      5         80.0                     4  ...   
...          ...           ...    ...          ...                   ...  ...   
4496           0             0      0          0.0                     0  ...   
4497           0             0      0          0.0                     0  ...   
4498           0             0      0          0.0                     0  ...   
4499           0             0      0          0.0                     0  ...   
4500           0             0      0          0.0                     0  ...   

      bowl_fp_avg  bowl_opp_avg  bowl_ven_avg  bowl_inn_avg  bowl_run_avg  \
0       58.000000     31.000000         31.00     44.500000     21.500000   
1       37.333333     25.000000         25.00     25.000000     22.750000   
2       27.000000     72.000000         72.00     48.500000     27.666667   
3       33.000000      0.000000         22.00     32.333333     26.500000   
4       22.000000     57.000000         36.75     36.666667     26.333333   
...           ...           ...           ...           ...           ...   
4496    32.000000     25.000000         25.00     32.000000     35.000000   
4497    43.000000     43.090909         56.00     35.259259     27.698413   
4498    22.000000     44.750000         85.00     27.461538     20.703704   
4499    41.666667     22.642857         31.60     33.101449     26.117284   
4500    35.333333     37.666667         38.40     33.753086     24.204225   

       eco_avg  maiden_avg  wicket_avg  bowl_over_avg  rating  
0     5.833333    0.000000    1.500000       3.500000     8.0  
1     7.583333    0.000000    1.250000       3.000000     8.0  
2     8.180556    0.000000    1.333333       3.333333     8.0  
3     9.010417    0.000000    1.000000       3.000000     9.5  
4     8.703704    0.000000    1.222222       3.111111     8.0  
...        ...         ...         ...            ...     ...  
4496  9.700000    0.000000    1.400000       3.600000   

In [ ]:
# plt.style.use('seaborn-whitegrid')
x = original_data["rating"].values    #storing the values of ratings in an array
encoded=[];                         
for w in x :                          #for loop over the rating column
    if(w==9):                         
        encoded.append("9")           #if w = 9; then encode it as 9  
    elif(w==9.5 ):                    
        encoded.append("9.5")         #if w = 9.5; then encode it as 9.5
    elif(w==10):
        encoded.append("10")          #if w = 10; then encode it as 10
    elif(w==8 ):
        encoded.append("8")           #if w = 8; then encode it as 8
    elif(w==8.5 ):
        encoded.append("8.5")         #if w = 8.5; then encode it as 8.5
    
encoded   
    
#     if(w>=0 and w<=20):
#         encoded.append(1)
#     if(w>20 and w<=49):
#         encoded.append(2)
#     if(w>49 and w<=74):
#         encoded.append(3)
# #     if(w>74 and w<=110):
# #         encoded.append(4)
#     if(w>74):
#         encoded.append(4)
        




['8',
 '8',
 '8',
 '9.5',
 '8',
 '8.5',
 '8.5',
 '8',
 '8.5',
 '8',
 '8.5',
 '8',
 '9.5',
 '8.5',
 '8',
 '8.5',
 '9.5',
 '9.5',
 '8',
 '8.5',
 '8.5',
 '8.5',
 '8',
 '9',
 '8',
 '8',
 '8',
 '8.5',
 '8',
 '8',
 '8',
 '10',
 '10',
 '8.5',
 '8.5',
 '8.5',
 '8',
 '8.5',
 '8.5',
 '8.5',
 '8',
 '8.5',
 '10',
 '8.5',
 '8.5',
 '9',
 '8.5',
 '8.5',
 '8',
 '10',
 '8.5',
 '8',
 '8',
 '10',
 '8',
 '9',
 '8.5',
 '8.5',
 '10',
 '8',
 '8',
 '8',
 '8',
 '8.5',
 '8',
 '9',
 '8',
 '8',
 '8',
 '9',
 '9.5',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8',
 '9',
 '8.5',
 '9',
 '8',
 '9.5',
 '8',
 '8.5',
 '8',
 '8',
 '9',
 '8',
 '8',
 '8.5',
 '10',
 '8',
 '8',
 '8.5',
 '8.5',
 '8',
 '8.5',
 '10',
 '8',
 '8',
 '8.5',
 '8.5',
 '8.5',
 '9.5',
 '8.5',
 '8',
 '8',
 '8.5',
 '8.5',
 '8',
 '8',
 '8',
 '8',
 '8.5',
 '8.5',
 '10',
 '9',
 '8.5',
 '8.5',
 '9.5',
 '8.5',
 '8.5',
 '8.5',
 '9',
 '8',
 '8.5',
 '8.5',
 '8',
 '9',
 '8.5',
 '9.5',
 '8.5',
 '8',
 '8',
 '9',
 '8',
 '10',
 '9.5'

In [ ]:
original_data['good_player']=encoded                                      #replacing the values in the column as the encoded values


le = preprocessing.LabelEncoder()                                         #Converting string labels into numbers

venue_encoded=le.fit_transform(original_data['venue'])                    #this will take the values of the venues in total and return it as encoded labels 
print(venue_encoded)

name_encoded=le.fit_transform(original_data['wicket_keeper_batsman'])     #this will take the values of the wicketkeeper batsman i.e. the role of the player is wicketkeeper batsman in total and return it as encoded labels 
print(name_encoded)

opp_team_encoded=le.fit_transform(original_data['opposition_team'])       #this will take the values of the opposition teams in total and return it as encoded labels 
print(opp_team_encoded)

original_data['venue_encoded']=venue_encoded                              #view the columns after encoding the labels
original_data['name_encoded']=name_encoded
original_data['opp_team_encoded']=opp_team_encoded

[35 16 24 ... 29  6  6]
[  0   0   0 ... 134  90  92]
[ 8  0  5 ...  7 14 10]


In [ ]:
x=original_data[['name_encoded','venue_encoded','opp_team_encoded','batting_avg_inning_points','batting_avg_venue_points','batting_avg_oppo_points','avg_strike_rate','avg_batsman_runs','bowl_fp_avg','bowl_opp_avg','bowl_ven_avg','bowl_inn_avg','bowl_run_avg','eco_avg','maiden_avg','wicket_avg','bowl_over_avg']]
# x=original_data[['name_encoded','venue_encoded','opp_team_encoded']]
# x=original_data[['name_encoded','venue_encoded','opp_team_encoded','avg_oppo_points','avg_venue_points','avg_inning_points','avg_batsman_runs','avg_strike_rate','avg_home_team_points','avg_total_points','avg_bound_runs']]
y=original_data['good_player']                                                        #taking required features or columns for the model training
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)    #dividing the train (75%) and test data (25%) with random state = 42 for data shuffling

model=GaussianNB()                                                                    #Naive Bayes model for classification
model.fit(x_train,y_train)                                                            #pass the training data in the model to predict the test data

y_test

1634     10
3687      9
4244      9
4005      9
468     8.5
       ... 
63      8.5
3010     10
3169    8.5
2694    8.5
4030      9
Name: good_player, Length: 1126, dtype: object

In [ ]:
y_pred=model.predict(x_test)      #predicting y_test for x_test using the model
y_pred

array(['10', '9', '9', ..., '8.5', '8.5', '9'], dtype='<U3')

In [ ]:
accuracy=accuracy_score(y_test,y_pred)*100    #printing the test accuracy of the data
accuracy

47.06927175843694

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix   #confusion matrix for test data vs predicted data
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 47  12  18   0   8]
 [ 23  91 101  65  24]
 [ 38  76 106  53  35]
 [  3  20  37 265  10]
 [ 11  21  28  13  21]]
              precision    recall  f1-score   support

          10       0.39      0.55      0.45        85
           8       0.41      0.30      0.35       304
         8.5       0.37      0.34      0.35       308
           9       0.67      0.79      0.73       335
         9.5       0.21      0.22      0.22        94

    accuracy                           0.47      1126
   macro avg       0.41      0.44      0.42      1126
weighted avg       0.46      0.47      0.46      1126



In [ ]:
from sklearn.model_selection import cross_val_score             #repeating the same steps for train and test data but using Random Forest Classifier
                                                                #accuracy is printed as well
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import RandomForestClassifier
x=original_data[['name_encoded','venue_encoded','opp_team_encoded','avg_oppo_points','avg_venue_points','avg_inning_points','avg_batsman_runs','avg_strike_rate','avg_home_team_points','avg_total_points','avg_bound_runs']]

# x=original_data[['name_encoded','venue_encoded','opp_team_encoded','batting_avg_inning_points','batting_avg_venue_points','batting_avg_oppo_points','avg_strike_rate','avg_batsman_runs' ,'bowl_fp_avg','bowl_opp_avg','bowl_ven_avg','bowl_inn_avg','bowl_run_avg','eco_avg','maiden_avg','wicket_avg','bowl_over_avg']]
# x=original_data[['name_encoded','venue_encoded','opp_team_encoded']]
# x=original_data[['name_encoded','venue_encoded','opp_team_encoded','avg_oppo_points','avg_venue_points','avg_inning_points','avg_batsman_runs','avg_strike_rate']]
# x=original_data[['name_encoded','venue_encoded','opp_team_encoded']]
# x=original_data[['name_encoded','venue_encoded','opp_team_encoded','avg_venue_points','avg_inning_points','avg_opposition_points','avg_batsman_runs','avg_strike_rate']]
y=original_data['good_player']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

rf = RandomForestClassifier(n_estimators=340)                   #Random Forest classifier with 340 decision trees 
rf.fit(x_train,y_train)

yhat = rf.predict(x_test)                                       #predicting the ytest using prediction of xtest

# t0 = time()
y_pred = rf.predict(x_test)
# print("done in %0.3fs" % (time() - t0))
print(classification_report(y_test, y_pred))                    #classification report for ytest vs ypred values

              precision    recall  f1-score   support

          10       0.56      0.51      0.54       239
           8       0.78      0.51      0.62       310
         8.5       0.48      0.61      0.54       519
           9       0.36      0.46      0.40       414
         9.5       0.44      0.12      0.19       162

    accuracy                           0.49      1644
   macro avg       0.53      0.44      0.46      1644
weighted avg       0.52      0.49      0.48      1644

